### ISSUE TITLE
Can't find the car_keypoints_train.json

### ISSUE THREAD

**Issue by Okkband** [dineshreddy91/Occlusion_Net#1]
Hi, i got a problem.
this is the problem snapshot.
![Selection_006](https://user-images.githubusercontent.com/52487802/60643513-e2795a00-9e65-11e9-963c-50b6f43da170.png)
i can find the train json file in the other folder.
But i don't know where should i put the json file.
Thank you.

**Comment by dineshreddy91** [comment]
The readme is updated with the location of the data folder and format let me know if you still face this issue

**Comment by Okkband** [comment]
> The readme is updated with the location of the data folder and format let me know if you still face this issue
Ok， thanks, the training command should be : sh train.sh occlusion_net datasets/carfusion   thanks.
