### ISSUE TITLE
sh test.sh --> docker: Error response from daemon: pull access denied for occlusion_net, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

### ISSUE THREAD

**Issue by samba723** [dineshreddy91/Occlusion_Net#10]
While running training
sh train.sh occlusion_net datasets/carfusion/train/

Im getting this error :--

**docker: Error response from daemon: pull access denied for occlusion_net, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.**

I have logged in to the Docker on my machine by using the 'docker login' command

**Comment by dineshreddy91** [comment]
Can you try using sudo to login to docker?
