### ISSUE TITLE
Conda having issue with Docker File

### ISSUE THREAD

**Issue by AmanGoyalNayan** [dineshreddy91/Occlusion_Net#11]
I was actually trying to build the docker and I got this error :

Sending build context to Docker daemon    102MB
Step 1/24 : ARG CUDA="10.0"
Step 2/24 : ARG CUDNN="7"
Step 3/24 : FROM nvidia/cuda:${CUDA}-cudnn${CUDNN}-devel-ubuntu16.04
 ---> 7bb1f0b039e1
Step 4/24 : RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
 ---> Using cache
 ---> ef324c7a213b
Step 5/24 : RUN apt-get update -y  && apt-get install -y apt-utils git curl ca-certificates bzip2 cmake tree htop bmon iotop g++-5  && apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender-dev vim feh wget xterm
 ---> Using cache
 ---> 44fc415a15ec
Step 6/24 : RUN curl -so /miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh  && chmod +x /miniconda.sh  && /miniconda.sh -b -p /miniconda  && rm /miniconda.sh
 ---> Using cache
 ---> 8b177a0162e7
Step 7/24 : ENV PATH=/miniconda/bin:$PATH
 ---> Using cache
 ---> d05c32bb7be4
Step 8/24 : RUN /miniconda/bin/conda install -y conda-build  && /miniconda/bin/conda create -y --name py36 python=3.6.7  && /miniconda/bin/conda clean -ya
 ---> Running in 09b35533c02b
/bin/sh: 1: /miniconda/bin/conda: not found
The command '/bin/sh -c /miniconda/bin/conda install -y conda-build  && /miniconda/bin/conda create -y --name py36 python=3.6.7  && /miniconda/bin/conda clean -ya' returned a non-zero code: 127

Kindly let me know the resolution as soon as possible.

**Comment by CedricVandelaer** [comment]
Hi @AmanGoyalNayan , I had the same problem but it turned out it could be fixed by replacing line 14 from:
`curl -so /miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh`
to:
`wget -O /miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh`

since the file was simply not downloading using curl and as a consequence subsequent steps failed
