### ISSUE TITLE
Enabling the 3D graph network head seems to produce bad outputs by default

### ISSUE THREAD

**Issue by CedricVandelaer** [dineshreddy91/Occlusion_Net#12]
Hello,

First of all thanks for creating and sharing this work. I have a question though. I have used the code on some traffic intersection images we have collected in Belgium. The output is pretty good but we only got 2D outputs. 

I have then enabled the KGNN3D setting in the config file, but now the outputs get really bad (see before and after picture). I was wondering if you have any idea why this is the case or how to improve this? I used the pretrained weights, but maybe the network wasn't yet trained using the 3D head?

Without 3D:
![test3](https://user-images.githubusercontent.com/6420173/87133661-ee2d0700-c297-11ea-9c78-0c251fa4f15e.jpg)

With 3D:
![test3_3D](https://user-images.githubusercontent.com/6420173/87133767-187ec480-c298-11ea-8ce3-e8652e66a1e9.jpg)

Best regards,
Cédric

**Comment by dineshreddy91** [comment]
The problem is the top view.. the 3D network is not trained on such views for it work.. I would just use the 2D detections and then fit a model using EPNP. Another way to address this problem is to retrain the network on this data.
