### ISSUE TITLE
Person keypoint detection not working

### ISSUE THREAD

**Issue by AkhileshV** [dineshreddy91/Occlusion_Net#13]
Occlusion_Net/lib/predictor.py", line 617, in vis_keypoints_person
    p2 = kps[0, i2], kps[1, i2]
IndexError: index 14 is out of bounds for axis 1 with size 14

**Comment by dineshreddy91** [comment]
The trained network currently only supports vehicle keypoints. Person keypoints is not yet incorporated into the framework.

**Comment by leon532** [comment]
@dineshreddy91  Thanks for sharing your great work. Did you test the performance of OcclusionNet on person keypoint datasets? How is the effect?

**Comment by dineshreddy91** [comment]
The theory in general should work great for humans as well. The datasets are widely available for persons online. So all you have to do is train the method on the dataset.

**Comment by leon532** [comment]
@dineshreddy91 Thanks.
