### ISSUE TITLE
How to handle cars without annotations in training

### ISSUE THREAD

**Issue by motokimura** [dineshreddy91/Occlusion_Net#14]
Hi, thank you for the code!

According to the following issue, some cars are not annotated in CarFusion dataset.
https://github.com/dineshreddy91/carfusion_to_coco/issues/1

When training Occlusion_Net with CarFusion dataset, how did you handle them?
It would be great if you could tell me where this handling is implemented in this repository.

Thank you in advance.

**Comment by dineshreddy91** [comment]
Currently occlusion-net is a top down approach so you can take any good vehicle detector like maskrcnn or Hrnet and then use the current data from car fusion to train the key point head. We used the same methodology for the occlusion-net. But if you are using bottom up approaches like open pose. you need to mask the unannotated cars.

**Comment by motokimura** [comment]
Thank you for your quick reply.

So you mean you loaded pretrained maskrcnn weight at the beginning, and the detector part was frozen during training?
I guess un-annotated vehicles will degrade detector performance without freezing even if it is a top down approach.

**Comment by dineshreddy91** [comment]
yes. if you do not freeze the weights of the detector the accuracy will be lower.

**Comment by motokimura** [comment]
Thank you! I got it now.
