### ISSUE TITLE
Dataset format

### ISSUE THREAD

**Issue by muaz-urwa** [dineshreddy91/Occlusion_Net#15]
I downloaded the car fusion dataset. groundtruth files have this format:

335.11,609.53,1,0,1
254.76,604.49,2,0,2
302.03,609.53,3,0,1
213.17,605.12,4,0,2
337.63,589.05,5,0,2
299.82,586.62,6,0,2

I believe the format is: x,y, keypint_id, object_id, ?

I am not sure what the last digit in each row means. Is it occlusion/visibility ?

**Comment by dineshreddy91** [comment]
yes. the last column is the visibility of the keypoint. If they are occluded or visible.

**Comment by muaz-urwa** [comment]
Thank you. Just to confirm, 1 means visible and 2 means occluded.
