### ISSUE TITLE
Regarding new car keypoints

### ISSUE THREAD

**Issue by ch-ho00** [dineshreddy91/Occlusion_Net#17]
Hi. Above all, I would like to thank you for open-sourcing such a great work! I really appreciate the concept of the work and neat code. 

To give you a brief idea of what I am trying to do, I am trying to apply occlusion net for the case of multiple car classes (vehicle, bus, truck and motor cycle) while only utilizing the 2D KGNN encoder-decoder. As some classes share some keypoints while some do not (ex, vehicle, truck, bus share a certain number of keypoints but not all, while motorcycle keypoints do not share any with other classes), I am wondering which part of the code I should be modifying in order to embed my graph structure.

While looking at the code, I am assuming that attributes "off_diag, rel_rec, rel_send" of class graphRCNNFeatureExtractor are the part which embeds the geometric structure (adjacency matrix) of the car graph. So I have replaced attribute off_diag with the adjacency matrix that contains the structure of my total keypoints (all classes' keypoints). Would this be sufficient for me to modify for me to add 2D KGNN on top of my keypoint predicting network? Or are there any other parts I need to consider or have I understood the implementation in a wrong way?

Any response will be appreciated! Once again thanks for the great work.

**Comment by dineshreddy91** [comment]
This is definitely the way to solve multi-class occlusion problem. You should try incorporating the class as an additional feature as well. An important aspect for such cases is using the bounding box and training the interaction between different classes. I am not sure how to address this issue. May be spending more time to train interactions might be the way to go. Sorry for the late reply was busy with cvpr submission.

**Comment by ch-ho00** [comment]
Thank you for the reply.
I will try to train the interactions based on the classes predicted and let you know how it goes.
Good luck with the CVPR submission :)
