### ISSUE TITLE
Enabling the 3D graph network head seems to produce bad outputs

### ISSUE THREAD

**Issue by haezu** [dineshreddy91/Occlusion_Net#19]
Hi, thank you for the code!

I used pretrained weight and tried to inference with 3d gnn. But the result is bad. 
I find the same issue on closed inssue.
So, after learning by enabling 3D GNN, I tested again and the result was worse.
One strange thing is that the loss_kgnn3d value drops to 0.003 when training, but the result is weird.
The picture below is the result of 3d gnn enabled for the carfusion test image. 

I'm curious if this hasn't been improved yet, and I want to know how I can do it.

![13_8942](https://user-images.githubusercontent.com/46044118/104284802-f93a4b80-54f5-11eb-8cca-ceb1c170c456.jpg)

**Comment by dineshreddy91** [comment]
hi, We are still working on releasing the 3D part of the code. This is in the to-do list and shouls have a version by may which works on multiple cars.
