### ISSUE TITLE
About the trifocal loss 

### ISSUE THREAD

**Issue by panxkun** [dineshreddy91/Occlusion_Net#21]
Hi, Thanks for sharing the code.

I have a question about your implentation of trifocal loss. In paper, the formula 9 is using the trifocal tensor's point-point-point constraint, then 9 scalar are obtained and all of them should be constrainted to be 0. But in your code, I thought the variable `loss_trifocal` represent the trifocal loss, but the implentation is just mismatched with what I understood. 

![image](https://user-images.githubusercontent.com/44204704/117559608-61222c80-b0b9-11eb-9967-e3fe9532eea3.png)

did I misunderstand your code？

**Comment by dineshreddy91** [comment]
We compute the 3D locations using trifocal loss. This error nll_gaussian is only trying to reduce the distance between the computed 3D point from trifocal loss and the predicted 3D point.
