### ISSUE TITLE
error during evaluation

### ISSUE THREAD

**Issue by nhonth** [dineshreddy91/Occlusion_Net#3]
Thanks a lot for sharing the code. I was following along the instructions and was able to build the docker image and train the model using the `train_net.py` script. However, when I reached the last step of the script (`train_net.py`, line 233), which called `run_test(...)` function, I got the following error.

```
creating index...
index created!
2019-07-24 19:20:04,813 maskrcnn_benchmark.inference INFO: Start evaluation on keypoints_carfusion_train_cocostyle dataset(20187 images).
100%|##########| 20187/20187 [30:04<00:00, 12.15it/s]
2019-07-24 19:50:09,799 maskrcnn_benchmark.inference INFO: Total inference time: 0:30:04.985017 (0.08941323708630472 s / img per device, on 1 devices)
Traceback (most recent call last):
  File "train_net.py", line 237, in <module>
    main()
  File "train_net.py", line 233, in main
    run_test(cfg, model, args.distributed)
  File "train_net.py", line 161, in run_test
    output_folder=output_folder,
  File "/code/lib/inference.py", line 104, in inference
    **extra_args)
  File "/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/__init__.py", line 27, in evaluate
    raise NotImplementedError("Unsupported dataset type {}.".format(dataset_name))
NotImplementedError: Unsupported dataset type CARFUSIONDataset.
COMET INFO: ----------------------------
```
It appears that the error was because  `evaluate(...)` (a function in the `maskrcnn-benchmark` package) does not know about `CARFUSIONDataset`.

Do you have any thought on this error? Did you modify the `evaluate(...)` function?

**Comment by dineshreddy91** [comment]
CARFUSIONDataset is a function we implemented as a loader in our repository. If you are trying to evaluate on carfusion. you need to import the carfusion class in dataloader/datasets/carfusion

**Comment by lililiiiiiiiiii** [comment]
> CARFUSIONDataset is a function we implemented as a loader in our repository. If you are trying to evaluate on carfusion. you need to import the carfusion class in dataloader/datasets/carfusion. The testing loss and script is already computed in the do_train function

hello! I have the same problem, under the path of  dataloader/datasets/carfusion,there exists the carfusion class,but the evaluation of maskrcnn-benchmark don't contain carfusiondataset

**Comment by dineshreddy91** [comment]
> hello! I have the same problem, under the path of dataloader/datasets/carfusion,there exists the carfusion class,but the evaluation of maskrcnn-benchmark don't contain carfusiondataset

The function is not required anymore. Pull the latest code and that should be resolved
