### ISSUE TITLE
AttributeError: BBOX_AUG

### ISSUE THREAD

**Issue by hdjsjyl** [dineshreddy91/Occlusion_Net#4]
Thanks for sharing your excellent work. When I try to run it on my local machine, it shows the following error:
AttributeError: BBOX_AUG;
Any advice will be appreciated, thanks

**Comment by dineshreddy91** [comment]
Hey, Can you post the complete error for me to look at it.

Thanks,

**Comment by dineshreddy91** [comment]
This error is in Maskrcnn branch. Please use the git checkout of maskrcnn specified in the Docker file.
