### ISSUE TITLE
Using another 2D object detector 

### ISSUE THREAD

**Issue by moshanATucsd** [dineshreddy91/Occlusion_Net#6]
Hi,

Thanks for sharing the code! Could you kindly advice how could we use another 2D object detector?

**Comment by dineshreddy91** [comment]
currently the code is integrated with maskrcnn. You can always copy the lib/Occlusion_net head into your favorite detector and train the graph head.

**Comment by moshanATucsd** [comment]
Got it, thanks for your quick reply!
