### ISSUE TITLE
sh train.sh --> docker: invalid reference format: repository name must be lowercase.

### ISSUE THREAD

**Issue by rsingh2083** [dineshreddy91/Occlusion_Net#9]
While running training 
`sh train.sh occlusion_net ../Occlusion-Net/datasets/carfusion/train/`

Im getting this error :--
```
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
```

**Comment by dineshreddy91** [comment]
This is a generic error of how you are running the file. please follow the instructions here.

https://stackoverflow.com/questions/48522615/docker-error-invalid-reference-format-repository-name-must-be-lowercase
